# Generated by Django 4.2.3 on 2023-07-13 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.AutoField(primary_key=True, serialize=False)),
                ('date_opened', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overdraft_lim', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('dob', models.DateField(null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('zipcode', models.CharField(max_length=6, null=True)),
                ('ssn', models.CharField(max_length=9, null=True)),
                ('number_of_accounts', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateField()),
                ('transaction_desc', models.CharField(max_length=100)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingApp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('next_payment_due', models.DateField()),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateField()),
                ('loan_term', models.IntegerField()),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingApp.account')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateField()),
                ('transaction_desc', models.CharField(max_length=100)),
                ('last_payment_date', models.DateField()),
                ('next_payment_date', models.DateField()),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingApp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateField()),
                ('transaction_desc', models.CharField(max_length=100)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingApp.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingApp.customer'),
        ),
    ]
